# This is a basic workflow to help you get started with Actions

name: Moj pierwszy przeplyw

# Controls when the workflow will run
#on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#  schedule:
#    - cron: '*/2 * * * *'
on:
  workflow_dispatch:
    inputs:  
     WyborKlienta:
       description: 'Nasz Klient'
       required: true
       default: "Contoso"
       type: choice
       options:
          - Contoso
          - Arcacorp
          - Nwtraders
     nazwa_operatora:
        description: "Twoje imie i i nazwisko"
        required: false
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  moje_pierwsze_zadanie:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Sprawdzamy wersję Python
        run: python3 -V

      - name: Wyswietl aktualny katalog roboczy
        run: pwd

      - name: Wyswietl listę plikow
        run: ls -la

      - name: Konfiguracja cache
        uses: actions/cache@v4.3.0
        with:
          path: "*nftables*"
          key: ${{ runner.os }}-nftables
          restore-keys: ${{ runner.os }}-nftables
  

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Ustal klucz cache dla nftables
        id: get_nftables_key
        run: |
          URL="https://www.netfilter.org/projects/nftables/files/nftables-1.0.6.1.tar.xz"
          # Pobierz tylko nagłówki; wybierz ETag/Last-Modified, usuń CR
          META_HEADERS=$(curl -sI "$URL" | grep -iE '^(ETag|Last-Modified):' | tr -d '\r')
          echo "== Nagłówki do klucza =="
          echo "$META_HEADERS"
          # Zrób skrót SHA256 nagłówków jako 'revision'
          REVISION=$(printf '%s' "$META_HEADERS" | sha256sum | cut -d' ' -f1)
          # Fallback gdyby serwer nie wystawił nagłówków (rzadkie)
          if [ -z "$REVISION" ]; then
            REVISION="noheaders-$(date +%Y%m%d)"
          fi
          echo "revision=$REVISION" >> "$GITHUB_OUTPUT"
          echo "url=$URL" >> "$GITHUB_OUTPUT"

      # 2) Przywróć/zarezerwuj cache pliku
      - name: Przywróć cache nftables
        id: cache_nftables
        uses: actions/cache@v4
        with:
          path: nftables-1.0.6.1.tar.xz
          key: nftables-${{ steps.get_nftables_key.outputs.revision }}

      # 3) Pobierz plik tylko gdy cache nie został trafiony
      - name: Pobierz źródła nftables (gdy cache-miss)
        if: steps.cache_nftables.outputs.cache-hit != 'true'
        run: |
          wget -O nftables-1.0.6.1.tar.xz "${{ steps.get_nftables_key.outputs.url }}"
          ls -lh nftables-1.0.6.1.tar.xz

      
      - name: Wyswietl listę plikow
        run: ls -lRa

      - name: testujemy zmienne input
        run: |
          echo "Wybrałeś klienta: $KLIENT"
          echo "Podane imię i nazwisko: ${{ inputs.nazwa_operatora }}"
        env:
          KLIENT: ${{ inputs.wybor_klienta }}



