# This is a basic workflow to help you get started with Actions

name: Moj pierwszy przeplyw

# Controls when the workflow will run
#on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
#  schedule:
#    - cron: '*/2 * * * *'
on:
  workflow_dispatch:
    inputs:  
     WyborKlienta:
       description: 'Nasz Klient'
       required: true
       default: "Contoso"
       type: choice
       options:
          - Contoso
          - Arcacorp
          - Nwtraders
     nazwa_operatora:
        description: "Twoje imie i i nazwisko"
        required: false
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  moje_pierwsze_zadanie:
    # The type of runner that the job will run on
    runs-on: ubuntu_latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      #- name: Sprawdzamy wersję Python
        #run: python -V

      - name: Wyswietl aktualny katalog roboczy
        run: pwd

      - name: Wyswietl listę plikow
        run: ls -a
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      #- name: Wyswietl listę plikow
        #run: ls -a

      #- name: Setup Python
        #uses: actions/setup-python@v6.0.0
        #with:
          #python-version: '3.13.7'
    
      #- name: Sprawdzamy wersję Python
        #run: python -V     

      - name: Testujemy zmienne input
        run: |
          echo "Wybrany klient to: $Klient"
          echo "Wskazany operator to: $Operator"
        env:
          Klient: ${{ inputs.WyborKlienta }}
          Operator: ${{ inputs.nazwa_operatora }}
