name: Przykladowy warunkowy przeplyw

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Wyswietl podstawowe informacje
        run: |
          echo "Uruchomiono przeplyw GitHub Actions"
          echo "Aktualna data: $(date)"

      - name: Pobierz wersje jadra
        id: jadro_kroku
        run: |
          KERNEL=$(uname -r)
          echo "KERNEL=$KERNEL" >> $GITHUB_OUTPUT

      - name: Wyswietl informacje jesli jadro jest 6.x
        if: startsWith(steps.jadro_kroku.outputs.KERNEL, '6.')
        run: echo "Wykryto jadro 6.x: warunkowy step zostal wykonany!"

      - name: Inny komunikat dla innego jadra
        if: ${{ !startsWith(steps.jadro_kroku.outputs.KERNEL, '6.') }}
        run: echo "Wykryto jadro inne niz 6.x — ten step zostal wykonany zamiast poprzedniego."
